Repository chandur626/TeachersPetBot, pull requests merged in 2021-12, with the labels that each got.

#52 updating docs links for email and event related changes
  README.md
Labels: documentation

#55 adding email address config and project event to help
  src/bot.py
  src/help_command.py
  test/test_help.py
Labels: documentation, enhancement

#56 Issue 33/doc/create project3 rubric
  docs/proj3rubric.md
Labels: documentation

#57 updating the contributing file
  CONTRIBUTING.md
Labels: documentation

#45 Issue 12/task/admin charts
  data/charts/chartstorage.json
  requirements.txt
  src/bot.py
  src/help_command.py
  test/test_chart.py
  test/tests.py
Labels: enhancement
